# Generated by Django 4.2.25 on 2025-10-20 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeographicalPresence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_name', models.CharField(max_length=150)),
                ('region_code', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProductionBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('inner_path', models.BooleanField()),
                ('path', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RegionAdress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress_name', models.TextField()),
                ('geographical_presence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainSite.geographicalpresence')),
            ],
        ),
        migrations.CreateModel(
            name='PageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_uuid', models.CharField(max_length=150)),
                ('title', models.CharField(max_length=100)),
                ('sub_title', models.CharField(max_length=350)),
                ('production', models.ManyToManyField(to='mainSite.productionbase')),
            ],
        ),
    ]
