# Generated by Django 4.2.25 on 2025-10-20 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainSite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(max_length=150)),
                ('part_text', models.CharField(blank=True, max_length=350)),
                ('product_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainSite.productionbase')),
            ],
        ),
    ]
