# Generated by Django 4.2.25 on 2025-10-20 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainSite', '0002_productpart'),
    ]

    operations = [
        migrations.AddField(
            model_name='regionadress',
            name='visible_on_site',
            field=models.BooleanField(default=False),
        ),
    ]
