# Generated by Django 4.2.25 on 2025-10-25 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainSite', '0005_producttype_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_img',
            field=models.FileField(blank=True, upload_to='media/production/'),
        ),
    ]
