# Generated by Django 4.2.25 on 2025-10-27 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainSite', '0006_product_product_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=350)),
                ('main_img', models.FileField(blank=True, upload_to='portfolio/')),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='product_img',
            field=models.FileField(blank=True, upload_to='production/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=350),
        ),
        migrations.CreateModel(
            name='PortfolioImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt', models.CharField(max_length=350)),
                ('image_link', models.FileField(blank=True, upload_to='portfolio/')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='mainSite.portfolio')),
            ],
        ),
    ]
