# Generated by Django 4.2.25 on 2025-10-27 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainSite', '0007_portfolio_alter_product_product_img_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolio',
            options={'verbose_name': 'Портфолио', 'verbose_name_plural': 'Портфолио'},
        ),
        migrations.AlterModelOptions(
            name='portfolioimage',
            options={'verbose_name': 'Изображение', 'verbose_name_plural': 'Изображения'},
        ),
        migrations.AddField(
            model_name='portfolio',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True, verbose_name='URL-ссылка'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='main_img',
            field=models.FileField(upload_to='portfolio/', verbose_name='Главное изображение'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='title',
            field=models.CharField(max_length=350, verbose_name='Наименование портфолио'),
        ),
        migrations.AlterField(
            model_name='portfolioimage',
            name='alt',
            field=models.CharField(max_length=150, verbose_name='Описание к изображению'),
        ),
        migrations.AlterField(
            model_name='portfolioimage',
            name='image_link',
            field=models.FileField(upload_to='portfolio/', verbose_name='Изображение'),
        ),
    ]
