# Generated by Django 4.2.25 on 2025-10-29 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainSite', '0008_alter_portfolio_options_alter_portfolioimage_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnologyPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_content', models.TextField()),
                ('last_update', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Страница "Технолногии"',
                'verbose_name_plural': 'Страница "Технологии"',
            },
        ),
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name': 'Страница "О нас"', 'verbose_name_plural': 'Страница "О нас"'},
        ),
        migrations.AlterModelOptions(
            name='geographicalpresence',
            options={'verbose_name': 'Регион и представительства', 'verbose_name_plural': 'Регионы и представительства'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AlterModelOptions(
            name='producttype',
            options={'verbose_name': 'Тип продукта (Админ)', 'verbose_name_plural': 'Типы продуктов (Админ)'},
        ),
        migrations.AlterModelOptions(
            name='regionadress',
            options={'verbose_name': 'Адрес представительства', 'verbose_name_plural': 'Адреса представительства'},
        ),
        migrations.AlterField(
            model_name='geographicalpresence',
            name='region_code',
            field=models.CharField(max_length=50, verbose_name='КОД'),
        ),
        migrations.AlterField(
            model_name='geographicalpresence',
            name='region_name',
            field=models.CharField(max_length=150, verbose_name='Наименование региона'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_img',
            field=models.FileField(blank=True, upload_to='production/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=350, verbose_name='Наименование продукта'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainSite.producttype', verbose_name='Тип продукта'),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='product_type',
            field=models.CharField(max_length=150, verbose_name='Тип продукта'),
        ),
        migrations.AlterField(
            model_name='regionadress',
            name='adress_name',
            field=models.TextField(verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='regionadress',
            name='geographical_presence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adresses', to='mainSite.geographicalpresence'),
        ),
        migrations.AlterField(
            model_name='regionadress',
            name='visible_on_site',
            field=models.BooleanField(default=False, verbose_name='Включить на сайте?'),
        ),
    ]
