# Generated by Django 4.2.25 on 2025-10-29 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainSite', '0009_technologypagecontent_alter_aboutus_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75, verbose_name='Наименование вакансии')),
                ('region', models.CharField(blank=True, default='Трехгорный', help_text='Если не указать, атвтоматически будет установлено "Трехгорный"', max_length=75, verbose_name='Город для работы')),
                ('work_schedule', models.CharField(default='5/2', max_length=15, verbose_name='График работы')),
                ('salary', models.IntegerField(blank=True, verbose_name='Размер оплаты труда')),
                ('requirements', models.TextField(blank=True, help_text='Требования необходимо указывать через запятую', verbose_name='Требования')),
                ('responsibilities', models.TextField(blank=True, help_text='Обязанности необходимо указывать через запятую', verbose_name='Обязанности')),
                ('isActive', models.BooleanField(verbose_name='Активная вакансия?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Заявка создана')),
                ('last_update', models.DateTimeField(verbose_name='Последнее обновление')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
            },
        ),
        migrations.CreateModel(
            name='VacanciesPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority_title', models.CharField(max_length=50, verbose_name='Заголовок')),
                ('priority_text', models.CharField(max_length=100, verbose_name='Дополнительное описание')),
                ('priority_img', models.FileField(upload_to='vacancies_page_content/', verbose_name='картинка (только в формате svg)')),
                ('last_update', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Страница "Вакансии"',
                'verbose_name_plural': 'Страница "Вакансии"',
            },
        ),
    ]
