# Generated by Django 4.2.25 on 2025-10-29 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainSite', '0012_alter_vacanciespagecontent_class_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacanciespagecontent',
            name='class_name',
            field=models.CharField(blank=True, default='None', help_text='Не менять', max_length=150, verbose_name='Класс для страницы'),
        ),
    ]
