# Generated by Django 4.2.25 on 2025-10-30 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainSite', '0013_alter_vacanciespagecontent_class_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='VacanciesApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(max_length=100, verbose_name='ФИО кандидата')),
                ('candidate_birthday_desire_income', models.TextField(blank=True, default='Не указаны', verbose_name='Дата и место рождения')),
                ('candidate_adress', models.CharField(blank=True, default='Не указан', max_length=200, verbose_name='Место жительства')),
                ('candidate_education_level', models.CharField(max_length=150, verbose_name='Уровень образования кандидата')),
                ('candidate_subeducation_level', models.TextField(blank=True, default='Не указано', verbose_name='Дополнительное образование кандидата')),
                ('candidate_marital_status', models.CharField(max_length=50, verbose_name='Семейное положение')),
                ('candidate_desire_income', models.IntegerField(blank=True, default=0, verbose_name='Уровень желаемого дохода')),
                ('candidate_email', models.CharField(max_length=100, verbose_name='Email кандидата')),
                ('candidate_tel', models.CharField(max_length=20, verbose_name='Телефон кандидата')),
                ('candidate_information', models.TextField(blank=True, default='Не указано дополнительных сведений', verbose_name='Дополнительная информация о кандидате')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to='mainSite.vacancies')),
            ],
            options={
                'verbose_name': 'Отклик на вакансию',
                'verbose_name_plural': 'Отклики на вакансии',
            },
        ),
    ]
