# Generated by Django 4.2.25 on 2025-10-30 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainSite', '0014_vacanciesapplication'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacanciesapplication',
            old_name='candidate_birthday_desire_income',
            new_name='candidate_birthday',
        ),
        migrations.AddField(
            model_name='vacanciesapplication',
            name='candidate_resume',
            field=models.FileField(blank=True, upload_to='', verbose_name='Резюме кандидата'),
        ),
    ]
