# Generated by Django 4.2.25 on 2025-10-30 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainSite', '0015_rename_candidate_birthday_desire_income_vacanciesapplication_candidate_birthday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacanciesapplication',
            name='candidate_resume',
            field=models.FileField(blank=True, upload_to='candidate_resume/', verbose_name='Резюме кандидата'),
        ),
    ]
