# Generated by Django 4.2.25 on 2025-11-18 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainSite', '0016_alter_vacanciesapplication_candidate_resume'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(max_length=100, verbose_name='Наименование организации')),
                ('org_adress', models.CharField(max_length=150, verbose_name='Адрес организации')),
                ('org_phone', models.CharField(max_length=150, verbose_name='Телефон организации')),
                ('org_fax', models.CharField(max_length=150, verbose_name='Факс организации')),
                ('org_email', models.CharField(max_length=150, verbose_name='Email организации')),
            ],
            options={
                'verbose_name': 'Контакт организации',
                'verbose_name_plural': 'Контакты организации',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumer_name', models.CharField(max_length=100, verbose_name='Имя отправителя')),
                ('consumer_email', models.CharField(max_length=100, verbose_name='Email отправителя')),
                ('consumer_tel', models.CharField(max_length=100, verbose_name='Телефон отправителя')),
                ('consumer_message', models.TextField(blank=True, default='Нет описания', verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Обращение с проектом',
                'verbose_name_plural': 'Обращения с проектами',
            },
        ),
    ]
