# Generated by Django 4.2.25 on 2025-11-19 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainSite', '0017_contactpage_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rewards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_title', models.CharField(max_length=100, verbose_name='Заголовок изображения')),
                ('reward_img', models.FileField(upload_to='rewards/', verbose_name='Изображение награды')),
                ('reward_description', models.TextField(default='Нет описания', verbose_name='Краткое описание')),
            ],
            options={
                'verbose_name': 'Награда',
                'verbose_name_plural': 'Награды',
            },
        ),
    ]
