# Generated by Django 4.2.25 on 2025-11-19 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainSite', '0018_rewards'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewards',
            name='isActive',
            field=models.BooleanField(default=True, verbose_name='Активная награда?'),
        ),
    ]
