# Generated by Django 4.2.25 on 2025-11-19 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainSite', '0019_rewards_isactive'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=350, verbose_name='Заголовок статьи')),
                ('article_text', models.TextField(verbose_name='Текст статьи')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='URL-ссылка')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
            },
        ),
    ]
