# Generated by Django 4.2.25 on 2025-11-19 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainSite', '0021_news_articles_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sert_title', models.CharField(max_length=100, verbose_name='Заголовок сертификата')),
                ('sert_description', models.TextField(default='Нет описания', verbose_name='Краткое описание')),
                ('sert_img', models.FileField(upload_to='sertificates/', verbose_name='Изображение сертификата')),
                ('isActive', models.BooleanField(default=True, verbose_name='Активная награда?')),
            ],
            options={
                'verbose_name': 'Серитфикат',
                'verbose_name_plural': 'Сертификаты',
            },
        ),
    ]
