# Generated by Django 4.2.25 on 2025-11-19 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainSite', '0022_sertificate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_title', models.CharField(max_length=100, verbose_name='Название технического свидетельства')),
                ('doc_description', models.TextField(default='Нет описания', verbose_name='Краткое описание')),
                ('doc_img', models.FileField(upload_to='documents/', verbose_name='Изображение технического свидетельства')),
                ('isActive', models.BooleanField(default=True, verbose_name='Активный документ?')),
            ],
            options={
                'verbose_name': 'Техническое свидетельство',
                'verbose_name_plural': 'Технические свидетельства',
            },
        ),
        migrations.AlterField(
            model_name='sertificate',
            name='isActive',
            field=models.BooleanField(default=True, verbose_name='Активный сертификат?'),
        ),
    ]
