# Generated by Django 4.2.25 on 2025-11-19 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainSite', '0023_documents_alter_sertificate_isactive'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='title_img',
            field=models.FileField(default=None, upload_to='news/title-img/', verbose_name='Главное изображение новости'),
            preserve_default=False,
        ),
    ]
