# Generated by Django 4.2.25 on 2025-11-19 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainSite', '0024_news_title_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='prev_text',
            field=models.CharField(blank=True, max_length=150, verbose_name='Превью новости'),
        ),
    ]
