# Generated by Django 4.2.25 on 2025-11-23 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainSite', '0025_news_prev_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacadeSystemBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facade_name', models.CharField(max_length=100, verbose_name='Наименование типа фасадной системы')),
                ('facade_description', models.TextField(default='Нет описания', verbose_name='Описание системы')),
                ('facade_base_slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='URL-ссылка')),
            ],
            options={
                'verbose_name': 'Тип фасадной системы',
                'verbose_name_plural': 'Типы фасадных систем',
            },
        ),
        migrations.CreateModel(
            name='FacadeSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fs_name', models.CharField(max_length=100, verbose_name='Наименование фасадной системы')),
                ('fs_subtext', models.CharField(max_length=100, verbose_name='Подпись для фасадной системы')),
                ('fs_description', models.TextField(default='Нет описания', verbose_name='Описание системы')),
                ('fs_slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='URL-ссылка')),
                ('fs_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='systems', to='mainSite.facadesystembase', verbose_name='Тип системы')),
            ],
            options={
                'verbose_name': 'Фасадная система',
                'verbose_name_plural': 'Фасадные системы',
            },
        ),
    ]
