# Generated by Django 4.2.25 on 2025-11-23 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainSite', '0026_facadesystembase_facadesystem'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacadeSystemStartPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fs_page_content', models.TextField(default='Нет описания', verbose_name='Контент стартовой сраницы')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Контент "Фасадные системы"',
                'verbose_name_plural': 'Контент "Фасадные системы"',
            },
        ),
    ]
