# Generated by Django 4.2.25 on 2025-11-23 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainSite', '0027_facadesystemstartpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='facadesystem',
            name='display_in_main',
            field=models.BooleanField(default=True, verbose_name='Показать на главной странице?'),
        ),
    ]
