# Generated by Django 4.2.25 on 2025-11-23 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainSite', '0028_facadesystem_display_in_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='facadesystem',
            name='main_img',
            field=models.FileField(default='', upload_to='fasad_img/', verbose_name='Заглавное изображение (для главной страницы)'),
            preserve_default=False,
        ),
    ]
