# Generated by Django 4.2.25 on 2025-11-23 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainSite', '0029_facadesystem_main_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='facadesystem',
            name='prev_text',
            field=models.CharField(blank=True, max_length=150, verbose_name='Превью описания'),
        ),
    ]
