# Generated by Django 4.2.26 on 2025-11-27 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainSite', '0030_facadesystem_prev_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepresentativesCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_country_name_rus', models.CharField(blank=True, max_length=50, verbose_name='Полное наименование страны на русском')),
                ('full_country_name_eng', models.CharField(blank=True, max_length=50, verbose_name='Полное наименование страны на английском')),
                ('short_country_name_rus', models.CharField(blank=True, max_length=10, verbose_name='Сокращенное наименование страны на русском')),
                ('short_country_name_eng', models.CharField(blank=True, max_length=10, verbose_name='Сокращенное наименование страны на английском')),
            ],
            options={
                'verbose_name': 'Страна (справочник)',
                'verbose_name_plural': 'Страны (справочник)',
            },
        ),
        migrations.CreateModel(
            name='Representatives',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=30, verbose_name='Город')),
                ('company_name', models.CharField(max_length=30, verbose_name='Наименование организации (полное)')),
                ('company_phone', models.CharField(max_length=50, verbose_name='Телефон организации')),
                ('company_email', models.CharField(max_length=50, verbose_name='Email организации')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainSite.representativescountry', verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'Представительство',
                'verbose_name_plural': 'Представительства',
            },
        ),
    ]
