# Generated by Django 4.2.26 on 2025-11-27 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainSite', '0031_representativescountry_representatives'),
    ]

    operations = [
        migrations.AddField(
            model_name='representatives',
            name='company_adress',
            field=models.CharField(blank=True, max_length=50, verbose_name='Адрес организации'),
        ),
    ]
