# Generated by Django 4.2.26 on 2025-11-27 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainSite', '0032_representatives_company_adress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='representatives',
            name='company_name',
            field=models.CharField(max_length=130, verbose_name='Наименование организации (полное)'),
        ),
    ]
