# Generated by Django 4.2.26 on 2026-04-16 05:41

from django.db import migrations, models
import mainSite.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainSite', '0035_geographicalpresence_city_offsets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='main_img',
            field=models.FileField(upload_to=mainSite.models.portfolio_upload_path, verbose_name='Главное изображение'),
        ),
        migrations.AlterField(
            model_name='portfolioimage',
            name='image_link',
            field=models.FileField(upload_to=mainSite.models.portfolio_image_upload_path, verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_img',
            field=models.FileField(blank=True, upload_to=mainSite.models.production_image_upload_path, verbose_name='Изображение'),
        ),
    ]
