# Generated by Django 4.2.26 on 2026-04-16 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainSite', '0036_alter_portfolio_main_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionbase',
            name='position',
            field=models.IntegerField(blank=True, null=True, verbose_name='Позиция на сайте'),
        ),
    ]
