# Generated by Django 4.2.26 on 2026-04-16 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainSite', '0037_productionbase_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttype',
            name='product_link',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='SLUG'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainSite.producttype', verbose_name='Тип продукта'),
        ),
    ]
