# Generated by Django 4.2.26 on 2026-04-17 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainSite', '0038_producttype_product_link_alter_product_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_description',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='Описание'),
        ),
    ]
