# Generated by Django 4.2.26 on 2026-04-17 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainSite', '0039_product_product_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sertificate',
            options={'verbose_name': 'Партнер', 'verbose_name_plural': 'Партнеры'},
        ),
        migrations.AlterField(
            model_name='sertificate',
            name='isActive',
            field=models.BooleanField(default=True, verbose_name='Активный парнер?'),
        ),
        migrations.AlterField(
            model_name='sertificate',
            name='sert_description',
            field=models.TextField(default='Нет описания', verbose_name='Дополнительная информация'),
        ),
        migrations.AlterField(
            model_name='sertificate',
            name='sert_img',
            field=models.FileField(upload_to='sertificates/', verbose_name='Логотип партнера'),
        ),
        migrations.AlterField(
            model_name='sertificate',
            name='sert_title',
            field=models.CharField(max_length=100, verbose_name='Наименование партнера'),
        ),
    ]
