# Generated by Django 4.2.26 on 2026-04-22 06:31

from django.db import migrations, models
import django.db.models.deletion
import mainSite.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainSite', '0040_alter_sertificate_options_alter_sertificate_isactive_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='architect',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='Архитектор'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='city',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='customer',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='Заказчик'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='installer',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='Монтажник'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='object_type',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='Тип объекта'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='region',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='Регион (страна)'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='title',
            field=models.CharField(max_length=350, verbose_name='Наименование объекта'),
        ),
        migrations.CreateModel(
            name='subSystemPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_name', models.CharField(max_length=150, verbose_name='Наименование системы')),
                ('system_description', models.CharField(blank=True, max_length=250, null=True, verbose_name='Описание системы (при наличии)')),
                ('system_image_link', models.FileField(upload_to=mainSite.models.portfolio_image_upload_path, verbose_name='Изображение')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_systems', to='mainSite.portfolio')),
            ],
            options={
                'verbose_name': 'Подсистема для портфолио',
                'verbose_name_plural': 'Подсистемы для портфолио',
            },
        ),
        migrations.CreateModel(
            name='claddingSystemPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cladding_name', models.CharField(max_length=150, verbose_name='Наименование облицовки')),
                ('cladding_description', models.CharField(blank=True, max_length=250, null=True, verbose_name='Описание (при наличии)')),
                ('cladding_image_link', models.CharField(blank=True, max_length=150, null=True, verbose_name='Изображение (при наличии)')),
                ('square', models.CharField(max_length=150, verbose_name='Площадь фасада')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cladding_systems', to='mainSite.portfolio')),
            ],
            options={
                'verbose_name': 'Облицовка для портфолио',
                'verbose_name_plural': 'Облицовки для портфолио',
            },
        ),
    ]
