# Generated by Django 4.2.26 on 2026-04-22 07:31

from django.db import migrations, models
import mainSite.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainSite', '0041_portfolio_architect_portfolio_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='year_comlited',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Год реализации'),
        ),
        migrations.AlterField(
            model_name='claddingsystemportfolio',
            name='square',
            field=models.FloatField(default=0, max_length=150, verbose_name='Площадь фасада'),
        ),
        migrations.AlterField(
            model_name='subsystemportfolio',
            name='system_image_link',
            field=models.FileField(upload_to=mainSite.models.portfolio_image_upload_path, verbose_name='Изображение (3D)'),
        ),
    ]
