# Generated by Django 4.2.26 on 2026-04-24 07:40

from django.db import migrations, models
import mainSite.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainSite', '0042_portfolio_year_comlited_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claddingsystemportfolio',
            name='cladding_image_link',
            field=models.FileField(blank=True, null=True, upload_to=mainSite.models.portfolio_image_upload_path, verbose_name='Изображение (при наличии)'),
        ),
    ]
