# Generated by Django 4.2.30 on 2026-04-25 11:56

from django.db import migrations, models


def migrate_portfolio_facade_systems(apps, schema_editor):
    Portfolio = apps.get_model('mainSite', 'Portfolio')
    FacadeSystem = apps.get_model('mainSite', 'FacadeSystem')
    SubSystemPortfolio = apps.get_model('mainSite', 'subSystemPortfolio')

    facade_systems_by_name = {
        (system.fs_name or '').strip().lower(): system.id
        for system in FacadeSystem.objects.all().only('id', 'fs_name')
        if (system.fs_name or '').strip()
    }

    for subsystem in SubSystemPortfolio.objects.select_related('portfolio').iterator():
        system_name = (subsystem.system_name or '').strip().lower()
        facade_system_id = facade_systems_by_name.get(system_name)
        if not facade_system_id:
            continue

        portfolio = Portfolio.objects.get(pk=subsystem.portfolio_id)
        portfolio.facade_systems.add(facade_system_id)


def reverse_migrate_portfolio_facade_systems(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('mainSite', '0043_alter_claddingsystemportfolio_cladding_image_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='facade_systems',
            field=models.ManyToManyField(blank=True, related_name='portfolios', to='mainSite.facadesystem', verbose_name='Фасадные системы'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='object_type',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='Тип объекта (Назначение)'),
        ),
        migrations.RunPython(migrate_portfolio_facade_systems, reverse_migrate_portfolio_facade_systems),
        migrations.DeleteModel(
            name='subSystemPortfolio',
        ),
    ]
