# Generated by Django 4.2.30 on 2026-06-11 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainSite', '0045_geographicalpresence_city_coordinates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
