# Generated by Django 4.2.30 on 2026-06-11 11:05

from django.db import migrations, models


def fill_empty_responsibilities(apps, schema_editor):
    vacancies = apps.get_model('mainSite', 'Vacancies')
    vacancies.objects.filter(responsibilities='').update(
        responsibilities='все подробности по телефону...'
    )


class Migration(migrations.Migration):

    dependencies = [
        ('mainSite', '0046_alter_product_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancies',
            name='responsibilities',
            field=models.TextField(blank=True, default='все подробности по телефону...', help_text='Обязанности необходимо разделять точкой с запятой', verbose_name='Обязанности'),
        ),
        migrations.AlterField(
            model_name='vacancies',
            name='salary',
            field=models.CharField(blank=True, max_length=100, verbose_name='Размер оплаты труда'),
        ),
        migrations.RunPython(
            fill_empty_responsibilities,
            migrations.RunPython.noop,
        ),
    ]
