# Generated by Django 4.2.30 on 2026-06-30 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainSite', '0047_alter_vacancies_responsibilities_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancies',
            name='region',
            field=models.CharField(blank=True, default='Трехгорный', help_text='Если не указать, атвтоматически будет установлено "Трехгорный"', max_length=250, verbose_name='Город для работы'),
        ),
        migrations.AlterField(
            model_name='vacancies',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Наименование вакансии'),
        ),
    ]
