# Generated by Django 4.2.30 on 2026-07-12 05:43

from django.db import migrations, models


def place_bracket_types_first(apps, schema_editor):
    ProductType = apps.get_model('mainSite', 'ProductType')
    ProductType.objects.filter(product_type__icontains='кронштейн').update(sort_order=10)
    ProductType.objects.filter(product_link__icontains='bracket').update(sort_order=10)


def reset_product_type_order(apps, schema_editor):
    ProductType = apps.get_model('mainSite', 'ProductType')
    ProductType.objects.update(sort_order=100)


class Migration(migrations.Migration):

    dependencies = [
        ('mainSite', '0048_alter_vacancies_region_alter_vacancies_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sort_order',
            field=models.PositiveIntegerField(blank=True, help_text='Оставьте пустым для сортировки по названию.', null=True, verbose_name='Позиция внутри раздела'),
        ),
        migrations.AddField(
            model_name='producttype',
            name='sort_order',
            field=models.PositiveIntegerField(default=100, verbose_name='Порядок вывода'),
        ),
        migrations.RunPython(place_bracket_types_first, reset_product_type_order),
    ]
