# Generated by Django 4.2.30 on 2026-07-21 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainSite', '0049_product_sort_order_producttype_sort_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='consent_recorded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время подтверждения'),
        ),
        migrations.AddField(
            model_name='project',
            name='personal_data_consent',
            field=models.BooleanField(default=False, verbose_name='Согласие на обработку ПД'),
        ),
        migrations.AddField(
            model_name='project',
            name='privacy_policy_acknowledged',
            field=models.BooleanField(default=False, verbose_name='С политикой ознакомлен'),
        ),
        migrations.AddField(
            model_name='project',
            name='privacy_policy_version',
            field=models.CharField(blank=True, max_length=71, verbose_name='Версия политики'),
        ),
        migrations.AddField(
            model_name='vacanciesapplication',
            name='consent_recorded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время подтверждения'),
        ),
        migrations.AddField(
            model_name='vacanciesapplication',
            name='personal_data_consent',
            field=models.BooleanField(default=False, verbose_name='Согласие на обработку ПД'),
        ),
        migrations.AddField(
            model_name='vacanciesapplication',
            name='privacy_policy_acknowledged',
            field=models.BooleanField(default=False, verbose_name='С политикой ознакомлен'),
        ),
        migrations.AddField(
            model_name='vacanciesapplication',
            name='privacy_policy_version',
            field=models.CharField(blank=True, max_length=71, verbose_name='Версия политики'),
        ),
    ]
